# Generated by Django 5.2.8 on 2025-11-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0003_company_category_company_founder_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='last_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
