# Generated by Django 5.2.8 on 2025-11-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0004_company_is_verified_company_last_verified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='show_in_leaderboard',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='category',
            field=models.CharField(choices=[('saas', 'SaaS'), ('youtuber_gamer', 'YouTuber - Gamer'), ('youtuber_content_creator', 'YouTuber - Content Creator'), ('youtuber_educational', 'YouTuber - Educational'), ('influencer_instagram', 'Influencer - Instagram'), ('influencer_facebook', 'Influencer - Facebook'), ('influencer_twitter', 'Influencer - Twitter/X'), ('indian_startup', 'Indian Startup'), ('film_entertainment', 'Film/Entertainment'), ('business_india', 'Business in India'), ('ecommerce', 'E-commerce'), ('consulting', 'Consulting'), ('agency', 'Agency'), ('other', 'Other')], default='other', max_length=100),
        ),
    ]
