# Generated by Django 4.2.26 on 2025-12-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0007_company_country_company_estimated_mrr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='founder_photo',
            field=models.ImageField(blank=True, null=True, upload_to='founder_photos/'),
        ),
    ]
