# Generated by Django 4.2.26 on 2025-12-07 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('revenue', '0008_company_founder_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('target_url', models.URLField(help_text='Where the ad links to')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ad_images/')),
                ('slot_id', models.CharField(choices=[('left_1', 'Left Sidebar 1'), ('left_2', 'Left Sidebar 2'), ('left_3', 'Left Sidebar 3'), ('left_4', 'Left Sidebar 4'), ('left_5', 'Left Sidebar 5'), ('right_1', 'Right Sidebar 1'), ('right_2', 'Right Sidebar 2'), ('right_3', 'Right Sidebar 3'), ('right_4', 'Right Sidebar 4'), ('right_5', 'Right Sidebar 5')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='revenue.company')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
