# Generated by Django 4.2.26 on 2025-12-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0009_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='confirmation_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='impressions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='live_notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
